INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
('drill', 'Drill', 15, 0, 1),
('hackerDevice', 'Hacker Device', 10, 0, 1),
('lockpick', 'Lockpick', 10, 0, 1),
('hammerwirecutter', 'Hammer And Wire Cutter', 10, 0, 1),
('accesscard', 'Access Card', 10, 0, 1),
('goldbar', 'Gold Bar', 100, 0, 1),
('goldwatch', 'Gold Watch', 200, 0, 1),
('goldnecklace', 'Gold Necklace', 150, 0, 1),
('diamond', 'Diamond', 10, 0, 1),